blank_issues_enabled: false
contact_links:
  - name: Datenschutzerklärung
    url: https://changnoi79.github.io/NextGenCapture-Site/privacy-policy/
    about: Informationen zur Verarbeitung von Daten in NextGen Capture.
